title: Inklings &mdash; Ideas to align Nashville's Suits, Developers, &amp; Designers.
url: http://www.inklin.gs
markdown: rdiscount
rdiscount:
  extensions: []
pygments: true
permalink: /:year/:month/:day/:title
auto: true
server: true
server_port: 3000
lsi: falsei
safe: false
paginate: 20

exclude:
- CNAME
