title: Inklings &mdash; Ideas to align Nashville's Suits, Designers, Developers, Testers & Analysts.
url: http://www.inklin.gs
markdown: rdiscount
rdiscount:
  extensions: []
pygments: true
permalink: /:year/:month/:day/:title
auto: true
server: true
server_port: 3000
lsi: falsei
safe: false
paginate: 8
exclude: ['README.md', 'CNAME', 'robots.txt', '404.html', '.gitignore', 'sitempap.xml']
