title: Inklings &mdash; Ideas to align Nashville's Suits, Developers, &amp; Designers.
#url: http://www.inklin.gs

markdown: rdiscount
pygments: true
permalink: /:year/:month/:day/:title

lsi: true
paginate: 20

exclude:
- CNAME
